### ISSUE TITLE
How can this plugin support nested JSON object?

### ISSUE THREAD

**Issue by GNANASEKHARKURA** [andreabbondanza/DewXamarinLocalization#3]
Its working fine with one to one properties in JSON but not with nested JSON object. Is there a way i can use nested JSON and get the localized string?

**Comment by andreabbondanza** [comment]
Hi. 
Sorry, but not with the current approach.
The localization library have like core the idea of "I search the key and if I find it, I'll return the value, otherwise I'll return back the key".
This kind of approach can't be compatible with nested dictionaries, because its hypotesis is that the json is a KEY-VALUE type only.
